language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install coveralls
script:
  - coverage run --omit test.py test.py -v
after_success:
  - coveralls
notifications:
  email: false
