language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
cache: pip
install:
  - pip install coveralls
script:
  - coverage run --source rule_n.py test.py -v
after_success:
  - coveralls
notifications:
  email: false
